### ISSUE TITLE
Ships with unnecessary node_modules dependencies?

### ISSUE THREAD

**Issue by Gama11** [smulyono/reveal-file-ext#1]
This extension comes with 7.4 MB worth of `node_modules`, which aren't needed at runtime I think? Still works fine after deleting that entire folder at least. :)

You may need a `.vscodeignore` file:
https://code.visualstudio.com/docs/extensions/publish-extension#_vscodeignore

**Comment by Gama11** [comment]
Actually, that's not quite true, it does stop working when just removing `node_modules`, but only because babel is in `dependencies` instead of `devDependencies` I think?

**Comment by smulyono** [comment]
@Gama11  babel-register was included since it is needed during runtime. If you download the latest version @1.2.7, that should have been removed. Where the generated transpiled code is shipped on the extension now.

**Comment by Gama11** [comment]
Looks like 1.2.7 only has 24 KB, that's a pretty drastic improvement percentage-wise. :)
